django_test/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('list/<slug:category_tag>/', views.ArticlesListView.as_view(), name ='articles-list'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article-detail'),
]

django_test/django_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_test/landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.LandingpageView.as_view(), name='landingpage'),
]

django_test/accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birthday = models.DateField(blank=True, null=True)

    def __str__(self):
        return "Profilo dell'utente {}".format(self.user.username)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)    
def update_user_profile(sender, instance, created, **kargs):
    if created:
        Profile.objects.create(user=instance) 

django_test/articles/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    STATUS_CHOICES = (
        ('DRAFT', 'Draft'),
        ('PUBLISHED', 'Published'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=PUBLISHED)
    
    TECNOLOGIA = 'TC'
    SPORT = 'SP'
    SALUTE = 'SL'
    TEMPO_LIBERO = 'TL'
    CATEGORIES = [    
        (TECNOLOGIA, 'Tecnologia'),
        (SPORT, 'Sport'),
        (SALUTE, 'Salute'),
        (TEMPO_LIBERO, 'Tempo Libero')
    ]
    category = models.CharField(max_length=2, choices=CATEGORIES, default='TL')
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    img = models.ImageField(upload_to='uploads/', blank=True)
    body = models.TextField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated', '-published')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('articles:article-detail', args=[self.slug, ])

django_test/landingpage/models.py
from django.db import models

# Create your models here.
class LandingPage(models.Model):
    message = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.message

django_test/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from .models import Profile

class RegistrationForm(UserCreationForm):

    first_name = forms.CharField(max_length=40, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=40, required=False, help_text='Optional.')
    birthday = forms.DateField(required=False, help_text='Optional. Format: YYYY-MM-DD.')
    email = forms.CharField(max_length=120, help_text='Required. Submit a valid email address.')
    
    # Permette di customizzare le informazioni della classe 
    class Meta: 
        model = User
        fields = ['username', 'first_name', 'last_name', 'birthday', 'email', 'password1', 'password2',]

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birthday',)

django_test/articles/views.py
# from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Article

# Create your views here.
class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context
    
class ArticlesListView(ListView):
    model = Article
    paginate_by = 3
    
    # Filtri di selezione 
    def get_queryset(self):
        tag = self.kwargs.get('category_tag', None)
        queryset = Article.objects.filter(status='PUBLISHED')
        if tag:
            queryset = Article.objects.filter(status='PUBLISHED').filter(category__in=[tag])
        return queryset

    def get_context_data(self, **kwargs):
        # Creazione context landingpage
        context = super().get_context_data(**kwargs)
        
        # context['articles_list'] = articles

        return context

django_test/landingpage/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.core.paginator import Paginator

from articles.models import Article

from .models import LandingPage


# Create your views here.
def index(request):
    obs_lst = LandingPage.objects.all()
    print("Primo messaggio da Landingpage:", obs_lst[0].message)

    context = {}
    context['message'] = obs_lst[0].message
    return render(request, 'landingpage/index.html', context=context)

class LandingpageView(TemplateView):
    template_name = 'landingpage/index.html'

    def get_context_data(self, **kwargs):
        # Creazione context landingpage
        context = super().get_context_data(**kwargs)

        # Creazione articoli e aggiunta a landingpage
        articles = Article.objects.filter(status='PUBLISHED')
        context['banner'] = articles[0]
        context['highlights'] = articles[1:3]
        articles_list = articles[3: ]
        context['articles_list'] = articles_list

        # Creazione paginatore e aggiunta a landingpage 
        paginator = Paginator(articles_list, 3)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        context['categories'] = Article.CATEGORIES

        return context

django_test/articles/templates/articles/article_detail.html
<h1>{{ object.title }}</h1>
<p>{{ object.body }}</p>
<p>Author: {{ object.author }}</p>
<p>Published: {{ object.published|date }}</p>

django_test/articles/templates/articles/article_list.html
{% extends "landingpage/index.html" %}

<!-- Lista articoli -->
{% block page_content %}
    {% include "articles/partials/_list_content.html" %}
{% endblock page_content %}

django_test/articles/templates/articles/partials/_list_content.html
<main class="container">
    <div class="row g-5">
        <!-- Section articles -->
        {% block section_articles %}
        {% include "landingpage/partials/_section_articles.html" %}
        {% endblock section_articles %}

        <!-- Sidebar -->
        {% block sidebar %}
        {% include "landingpage/partials/_sidebar.html" %}
        {% endblock sidebar %}

    </div>

</main>

django_test/landingpage/templates/landingpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <head>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Blog Template · Bootstrap v5.3</title>
    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.3/examples/blog/">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
          crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static '/css/blog.css' %}">
    <style> 
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap"
          rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
      </symbol>
    </svg>

    <!-- Options -->
    {% block options %}
      {% include "landingpage/partials/_options.html" %}
    {% endblock options %}
    <!-- Header - Navbar -->
    {% block header %}
      {% include "landingpage/partials/_header.html" %}
    {% endblock header %}
    <!-- Content -->
    {% block page_content %}
      {% include "landingpage/partials/_landingpage_content.html" %}
    {% endblock page_content %}
    <!-- Footer -->
    {% block footer %}
      {% include "landingpage/partials/_footer.html" %}
    {% endblock footer %}
    
    <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
    </script>
  </body>
</html>

django_test/landingpage/templates/landingpage/index_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <h1>{{ message }}</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

django_test/landingpage/templates/landingpage/partials/_banner_big.html
<!-- Banner -->
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
        <h1 class="display-4 fst-italic">{{ banner.title }}</h1>
        <p class="lead my-3">{{ banner.body|truncatewords:20 }}</p>
        <p class="lead mb-0"><a href="{{ banner.get_absolute_url }}" class="text-body-emphasis fw-bold">Continua a leggere...</a></p>
    </div>
</div>

django_test/landingpage/templates/landingpage/partials/_footer_credits.html
<!-- Footer Credits -->
<p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a
    href="https://twitter.com/mdo">@mdo</a>.</p>

django_test/landingpage/templates/landingpage/partials/_footer_nav.html
<!-- Footer Nav -->
<p class="mb-0">
    <a href="#">Back to top</a>
</p>

django_test/landingpage/templates/landingpage/partials/_header.html
<div class="container">
    <header class="border-bottom lh-1 py-3">
        <!-- Header -->
        {% block header_top %}
        {% include "landingpage/partials/_header_top.html" %}
        {% endblock %}

        <!-- Navbar -->
        {% block header_nav %}
        {% include "landingpage/partials/_header_nav.html" %}
        {% endblock %}

    </header>
</div>

django_test/landingpage/templates/landingpage/partials/_header_nav.html
<!-- Navbar -->
<div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">

      {% for category_tag, category_display_name in categories %}
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'articles:articles-list' category_tag %}">{{ category_display_name }}</a>
      {% endfor %}

    </nav>
  </div>

django_test/landingpage/templates/landingpage/partials/_header_top.html
<!-- Header -->
<div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
        <a class="link-secondary" href="#"></a>
    </div>
    <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'landingpage:landingpage' %}">My Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                viewBox="0 0 24 24">
                <title>Search</title>
                <circle cx="10.5" cy="10.5" r="7.5" />
                <path d="M21 21l-5.2-5.2" />
            </svg>
        </a>
        {% if user.is_authenticated %}
            <a class="text" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:logout' %}">Esci</a>
        {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:login' %}">Accedi</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:register' %}">Registrati</a>
        {% endif %}
    </div>
</div>

django_test/landingpage/templates/landingpage/partials/_landingpage_content.html
<!-- Content -->
<main class="container">
    <!-- Banner -->
    {% block banner %}
    {% include "landingpage/partials/_banner_big.html" %}
    {% endblock banner %}

    <!-- Section highlights -->
    {% block section_highlights %}
    {% include "landingpage/partials/_section_highlights.html" %}
    {% endblock section_highlights %}

    <div class="row g-5">
        <!-- Section articles -->
        {% block section_articles %}
        {% include "landingpage/partials/_section_articles.html" %}
        {% endblock section_articles %}

        <!-- Sidebar -->
        {% block sidebar %}
        {% include "landingpage/partials/_sidebar.html" %}
        {% endblock sidebar %}

    </div>

</main>

django_test/landingpage/templates/landingpage/partials/_list_archives.html
<!-- Archives -->
<div class="p-4">
      <h4 class="fst-italic">Archives</h4>
      <ol class="list-unstyled mb-0">
        <li>
          <a href="#">March 2021</a>
        </li>
        <li>
          <a href="#">February 2021</a>
        </li>
        <li>
          <a href="#">January 2021</a>
        </li>
        <li>
          <a href="#">December 2020</a>
        </li>
        <li>
          <a href="#">November 2020</a>
        </li>
        <li>
          <a href="#">October 2020</a>
        </li>
        <li>
          <a href="#">September 2020</a>
        </li>
        <li>
          <a href="#">August 2020</a>
        </li>
        <li>
          <a href="#">July 2020</a>
        </li>
        <li>
          <a href="#">June 2020</a>
        </li>
        <li>
          <a href="#">May 2020</a>
        </li>
        <li>
          <a href="#">April 2020</a>
        </li>
      </ol>
    </div>

django_test/landingpage/templates/landingpage/partials/_list_socials.html
<!-- Socials -->
<div class="p-4">
      <h4 class="fst-italic">Elsewhere</h4>
      <ol class="list-unstyled">
        <li>
          <a href="#">GitHub</a>
        </li>
        <li>
          <a href="#">Twitter</a>
        </li>
        <li>
          <a href="#">Facebook</a>
        </li>
      </ol>
</div>

django_test/landingpage/templates/landingpage/partials/_pagination.html
<nav class="blog-pagination">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-primary rounded-pill" href="?page=1">&laquo; first</a>
            <a class="btn btn-outline-primary rounded-pill" href="?page={{ page.previous_page_number }}">previous</a>
        {% else %}
            <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">first</a>
            <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">previous</a>
        {% endif %}

            Pagina {{ page.number }} di {{ page.paginator.num_pages }}.

        {% if page_obj.has_next %}
            <a class="btn btn-outline-primary rounded-pill" href="?page={{ page.next_page_number }}">next</a>
            <a class="btn btn-outline-primary rounded-pill" href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
        {% else %}
            <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">next</a>
            <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">last</a>
        {% endif %}
</nav>

django_test/landingpage/templates/landingpage/partials/_section_articles.html
<!-- Section articles -->
<div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
        Ultimi articoli inseriti
    </h3>

    {% for article in page_obj %}
    
    <article class="blog-post">
           
        <h2 class="display-5 link-body-emphasis mb-1">{{ article.title }}</h2>
        <p class="blog-post-meta">{{ article.published }} <a href="#">Admin</a></p>

        <p>{{ article.body }}</p>
    </article>

    {% endfor %}

    {% block pagination %}
        {% include "landingpage/partials/_pagination.html" with page=page_obj %}
    {% endblock pagination %}
    

</div>

django_test/landingpage/templates/landingpage/partials/_section_highlights.html
<!-- Section highlights -->
<div class="row mb-2">
    
    {% for highlight in highlights %}
    
        <!-- Highlights card -->
        {% block highlights_card_1 %}
            {% include "landingpage/partials/_highlights_card.html" with highlight=highlight %}
        {% endblock %}

    {% endfor %}

</div>

django_test/landingpage/templates/landingpage/partials/_sidebar.html
<!-- Sidebar -->
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem">
    <!-- About -->
    {% block widget_about %}
    {% include "landingpage/partials/_widget_about.html" %}
    {% endblock widget_about %}

    <!-- Post -->
    {% block widget_post %}
    {% include "landingpage/partials/_widget_post.html" %}
    {% endblock widget_post %}

    <!-- Archives -->
    {% block list_archives %}
    {% include "landingpage/partials/_list_archives.html" %}
    {% endblock list_archives %}

    <!-- Socials -->
    {% block list_socials %}
    {% include "landingpage/partials/_list_socials.html" %}
    {% endblock list_socials %}
    
  </div>
</div>

django_test/landingpage/templates/landingpage/partials/_widget_about.html
<!-- About -->
    <div class="p-4 mb-3 bg-body-tertiary rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Customize this section to tell your visitors a little bit about your publication,
            writers,
            content, or something else entirely. Totally up to you.</p>
    </div>